# Generated by Django 2.1.2 on 2018-12-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedMusicLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400)),
                ('artistName', models.CharField(max_length=100)),
                ('linkName', models.CharField(max_length=100)),
                ('linkSource', models.CharField(max_length=100)),
                ('link_type', models.CharField(choices=[('Demo', 'Demo'), ('TRACK', 'Track'), ('EP', 'EP'), ('ALBUM', 'Album'), ('SET', 'Set')], default='TRACK', max_length=5)),
                ('shared_date', models.DateTimeField(verbose_name='date shared')),
            ],
        ),
    ]
