# Generated by Django 2.1.2 on 2018-12-08 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeLinks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedmusiclink',
            old_name='artistName',
            new_name='artist_name',
        ),
        migrations.RenameField(
            model_name='sharedmusiclink',
            old_name='linkName',
            new_name='link_name',
        ),
        migrations.RenameField(
            model_name='sharedmusiclink',
            old_name='linkSource',
            new_name='link_source',
        ),
    ]
