# Generated by Django 2.1.2 on 2018-12-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeLinks', '0002_auto_20181208_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedmusiclink',
            name='status',
            field=models.IntegerField(choices=[(1, 'To_Listen'), (2, 'Done')], default=1),
        ),
    ]
