# Generated by Django 2.1.2 on 2018-12-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeLinks', '0003_sharedmusiclink_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedmusiclink',
            name='shared_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date shared'),
        ),
    ]
