# Generated by Django 2.1.2 on 2018-12-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeLinks', '0004_auto_20181209_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedmusiclink',
            name='shared_by',
            field=models.CharField(default='nayan vaish', max_length=100),
            preserve_default=False,
        ),
    ]
