# Generated by Django 2.1.2 on 2018-12-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeLinks', '0005_sharedmusiclink_shared_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedmusiclink',
            name='user_name',
            field=models.CharField(default='NayanVaish', max_length=100),
        ),
    ]
