# Generated by Django 2.1.2 on 2019-01-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeLinks', '0006_sharedmusiclink_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedmusiclink',
            name='link',
            field=models.CharField(error_messages={'unique': 'This email has already been registered.'}, max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='sharedmusiclink',
            name='user_name',
            field=models.CharField(db_index=True, default='NayanVaish', max_length=100),
        ),
    ]
