# Generated by Django 2.1.2 on 2019-01-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeLinks', '0007_auto_20190105_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedmusiclink',
            name='user_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
