# Generated by Django 2.1.2 on 2019-01-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeLinks', '0008_auto_20190105_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedmusiclink',
            name='link',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterUniqueTogether(
            name='sharedmusiclink',
            unique_together={('user_name', 'link')},
        ),
    ]
