# Generated by Django 2.1.2 on 2019-01-05 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeLinks', '0009_auto_20190105_2231'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharedmusiclink',
            unique_together=set(),
        ),
    ]
