version: '3'
volumes:
  pgdata:

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "python3 manage.py makemigrations storeLinks && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/music_sharing
    ports:
      - "8000:8000"
    depends_on:
      - db
